name: DevOpsLabs.yml

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  #.NET can be built on ubuntu
  dotnetbuild:
    runs-on: ubuntu-latest
    name: Install .NET Requirements, build project and test project
    steps:
      - uses: actions/checkout@v3
      - name: Install .NET Requirements
        uses: actions/setup-dotnet@v3
      - name: Restore nuget packages
        run: dotnet restore
      - name: Build .NET Project
        run: dotnet build --configuration Release --no-restore
      - name: Test .NET Project
        run: dotnet test --verbosity normal --no-restore --logger trx --results-directory "./UnitTestResults/DevOpsLabsUnitTests"
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: DevOpsLabsUnitTestResults
          path: ./UnitTestResults/DevOpsLabsUnitTests
        if: ${{ always() }}