# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  dotnetbuild:
    name: Build the .NET project
  dotnettesting:
    name: Run the .NET unit tests for the project
  dotnetpackaging:
    name: Set up the .NET project for packaging and pushing to the nuget feed